dinner = [
  'Salad'
  'Pizza'
  'Tacos'
  'Instant noodles'
  'Pad Thai'
  'Nachos'
  'Dumplings'
  'Pasta'
  'Kibbles'
  'carrots...'
]
bePolite = [
  ' '
  'Possibly'
  'Thinking it might be'
  'Feeling like'
  'Craving'
  'Left over'
  'Most likely,'
]

module.exports = (vivibot) ->
  vivibot.hear /Whats for dinner?/, (food) ->
    food.send food.random(bePolite) + ' ' + food.random(dinner)
  return

# ---
# generated by js2coffee 2.2.0
