streetName = [
  'Batman'
  'Homer'
  'Alice'
  'Dino'
  'Kenny'
  'Clark'
  'Harley Quin'
  'Toatoa'
  'Wolverene'
  'Peter Pan'
  'Robin'
]
streetType = [
  'St'
  'Ave'
  'Blv'
  'Alley'
  'Drive'
  'Run'
  'Lane'
  'Way'
  'Walk'
  'Cave'
  'Point'
]
city = [
  'Neverland'
  'Gotham'
  'Wonderland'
  'Kings landing'
  'Metropolis'
  'Bedrock'
  'South Park'
  'Silent Hill'
  'Arkham'
  'Whoville'
  'Emerald City'
]
stateAbbrev = [
  'NSW'
  'ACT'
  'VIC'
  'QLD'
  'SA'
  'WA'
  'TAS'
  'NT'
]

module.exports = (vivibot) ->
  vivibot.hear /Where are you now?/, (roam) ->
    streetNumber = Math.floor(Math.random() * 99)
    postCode = Math.floor(Math.random() * (7999 - 800) + 800)
    correspondingState = undefined
    if postCode <= 999
      correspondingState = stateAbbrev[7]
    else if postCode <= 7999 and postCode >= 7000
      correspondingState = stateAbbrev[6]
    else if postCode <= 6999 and postCode >= 6000
      correspondingState = stateAbbrev[5]
    else if postCode <= 5999 and postCode >= 5000
      correspondingState = stateAbbrev[4]
    else if postCode <= 4999 and postCode >= 4000
      correspondingState = stateAbbrev[3]
    else if postCode <= 3999 and postCode >= 3000
      correspondingState = stateAbbrev[2]
    else if postCode <= 2920 and postCode >= 2600
      correspondingState = stateAbbrev[1]
    else
      correspondingState = stateAbbrev[0]
    roam.send streetNumber + ' ' + roam.random(streetName) + ' ' + roam.random(streetType) + ' ' + roam.random(city) + ' ' + correspondingState + ' ' + postCode
  return

# ---
# generated by js2coffee 2.2.0
